# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6973de69cc5d831a0990bd7b4990f0ee490c2e42d9d8d4ea1e0b625eec68f34729008cfce4189d6237650b9f6ff65a184a5c9941c05c9f4e6b45435c223186b

test:
  secret_key_base: c25963931e0d79027fae333382886710cf548e6756295b2d6b33615d4d9c352db51aeb4436f15942eb4d95b9d1cb896b708685f2c13f52a04a1a519ab7bac8a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
